---
name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install --upgrade pip
          pip install pytest mocker pytest-mock
          python --version
          pytest --version
      - run: |
          sudo apt-get install cpanminus html-xml-utils xmlstarlet
          sudo cpanm -n -M https://cpan.metacpan.org --installdeps .
      - name: unit- and integration tests
        run: |
         make test-unit

  style:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/home/okurz/container/containers/os-autoinst-scripts-devel
    steps:
      - uses: actions/checkout@v4
      - name: Static checks
        run: |
          git config --global --add safe.directory .
          make checkstyle
